stages:
  - django3.2
  - django4.1
  - django4.2

.runtests:
  image: python:$PYTHON_VERSION
  before_script:
    - pip install django==$DJANGO_VERSION
    - pip install -e .
  script:
    - ./runtests.sh

# Django 3.2

django3.2-python3.8:
  stage: django3.2
  extends: .runtests
  variables:
    PYTHON_VERSION: "3.8"
    DJANGO_VERSION: "3.2"

django3.2-python3.9:
  stage: django3.2
  extends: .runtests
  variables:
    PYTHON_VERSION: "3.9"
    DJANGO_VERSION: "3.2"

django3.2-python3.10:
  stage: django3.2
  extends: .runtests
  variables:
    PYTHON_VERSION: "3.10"
    DJANGO_VERSION: "3.2"

django3.2-python3.11:
  stage: django3.2
  extends: .runtests
  variables:
    PYTHON_VERSION: "3.11"
    DJANGO_VERSION: "3.2"

# Django 4.1

django4.1-python3.8:
  stage: django4.1
  extends: .runtests
  variables:
    PYTHON_VERSION: "3.8"
    DJANGO_VERSION: "4.1"

django4.1-python3.9:
  stage: django4.1
  extends: .runtests
  variables:
    PYTHON_VERSION: "3.9"
    DJANGO_VERSION: "4.1"

django4.1-python3.10:
  stage: django4.1
  extends: .runtests
  variables:
    PYTHON_VERSION: "3.10"
    DJANGO_VERSION: "4.1"

django4.1-python3.11:
  stage: django4.1
  extends: .runtests
  variables:
    PYTHON_VERSION: "3.11"
    DJANGO_VERSION: "4.1"

# Django 4.2

django4.2-python3.8:
  stage: django4.2
  extends: .runtests
  variables:
    PYTHON_VERSION: "3.8"
    DJANGO_VERSION: "4.2"

django4.2-python3.9:
  stage: django4.2
  extends: .runtests
  variables:
    PYTHON_VERSION: "3.9"
    DJANGO_VERSION: "4.2"

django4.2-python3.10:
  stage: django4.2
  extends: .runtests
  variables:
    PYTHON_VERSION: "3.10"
    DJANGO_VERSION: "4.2"

django4.2-python3.11:
  stage: django4.2
  extends: .runtests
  variables:
    PYTHON_VERSION: "3.11"
    DJANGO_VERSION: "4.2"
